# Get all blogs
GET http://localhost:3001/api/blogs

###
# Get a specific blog
GET http://localhost:3001/api/blogs/67bcb53b768eb0b5e677ccd7

###
# Create a new blog
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "RESTful API Design",
    "author": "David Lee",
    "url": "http://example.com/restful-api",
    "likes": 12,
    "userId": "67c5eb7d51babaa1ea0d471b"
}

###
# Update a blog
PUT http://localhost:3001/api/blogs/67bcb644768eb0b5e677ccee
Content-Type: application/json

{
    "title": "Pravasi",
    "author": "Author Name",
    "url": "http://example.com/new-blog",
    "likes": 0,
    "userId": "67c5eb9651babaa1ea0d4721"
}

###
# Delete a blog
DELETE http://localhost:3001/api/blogs/67c5ea3f51babaa1ea0d46f2